apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hossign
  name: hossign
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hossign
  template:
    metadata:
      labels:
        app: hossign
    spec:
      containers:
      - image: fudgnl2/hossign:0.0.1
        name: hossign
        ports:
        - containerPort: 3000
          name: hossign