apiVersion: v1
kind: Service
metadata:
  labels:
    app: userlog
  name: userlog
  namespace: test
spec:
  type: NodePort
  ports:
  - name: 'userlog-service'
    port: 80
    targetPort: 3000
    nodePort: 30003
  selector:
    app: userlog
