apiVersion: v1
kind: Service
metadata:
  labels:
    app: usersignup
  name: usersignup
  namespace: test
spec:
  type: NodePort
  ports:
  - name: 'usersignup-service'
    port: 80
    targetPort: 3000
    nodePort: 30004
  selector:
    app: usersignup
