apiVersion: v1
kind: Service
metadata:
  labels:
    app: hoslog
  name: hoslog
  namespace: test
spec:
  type: NodePort
  ports:
  - name: 'hoslog-service'
    port: 80
    targetPort: 3000
    nodePort: 31003
  selector:
    app: hoslog
