apiVersion: v1
kind: Service
metadata:
  labels:
    app: hoslog
  name: hoslog
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: 'hoslog-service'
    port: 80
    targetPort: 3000
  selector:
    app: hoslog
