apiVersion: v1
kind: Service
metadata:
  labels:
    app: hosres
  name: hosres
  namespace: test
spec:
  type: NodePort
  ports:
  - name: 'hosres-service'
    port: 80
    targetPort: 3000
    nodePort: 31006
  selector:
    app: hosres
