apiVersion: v1
kind: Service
metadata:
  labels:
    app: hosres
  name: hosres
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: 'hosres-service'
    port: 80
    targetPort: 3000
  selector:
    app: hosres
