apiVersion: v1
kind: Service
metadata:
  labels:
    app: hossign
  name: hossign
  namespace: test
spec:
  type: NodePort
  ports:
  - name: 'hossign-service'
    port: 80
    targetPort: 3000
    nodePort: 31004
  selector:
    app: hossign
