apiVersion: v1
kind: Service
metadata:
  labels:
    app: hossign
  name: hossign
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: 'hossign-service'
    port: 80
    targetPort: 3000
  selector:
    app: hossign
