apiVersion: v1
kind: Service
metadata:
  labels:
    app: usermain
  name: usermain
  namespace: test
spec:
  type: NodePort
  ports:
  - name: 'usermain-service'
    port: 80
    targetPort: 3000
    nodePort: 30005
  selector:
    app: usermain