apiVersion: v1
kind: Service
metadata:
  labels:
    app: usersignup
  name: usersignup
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: 'usersignup-service'
    port: 80
    targetPort: 3000
  selector:
    app: usersignup
