apiVersion: v1
kind: Service
metadata:
  labels:
    app: usermain
  name: usermain
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: 'usermain-service'
    port: 80
    targetPort: 3000
  selector:
    app: usermain