apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: usermain
  name: usermain
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermain
  template:
    metadata:
      labels:
        app: usermain
    spec:
      containers:
      - image: fudgnl2/update:0.0.10
        name: usermain
        ports:
        - containerPort: 3000
          name: usermain